[general]
import = ["~/.config/alacritty/colors.toml"]

[terminal]
shell = { program = "/opt/homebrew/bin/fish" }

[env]
TERM = "xterm-256color"

[window]
opacity = 1
dimensions = { columns = 0, lines = 0 }
padding = { x = 6, y = 6 }
decorations = "None" # "Full" | "None" | "Transparent" | "Buttonless"
decorations_theme_variant = "Dark"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[scrolling]
history = 10000
multiplier = 10

[selection]
semantic_escape_chars = ",â”‚`|:\" ()[]{}<"
save_to_clipboard = true
